### ISSUE TITLE
Details to modify in the latest dev version (1.0.0-dev.3)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/least-squares-regression#1]
- [x] pre-set points should be 80% smaller than custom and have a white stroke
- [x] custom points should remain at 100% and have a black stroke
- [x] make the pile of points look more rounded and natural
- [x] make all text next to checkboxes 2 pts larger
- [x] align y = ax + b and sliders under equation readout
  ![screen shot 2014-12-15 at 12 36 08 pm](https://cloud.githubusercontent.com/assets/7852916/5442517/fa02feca-8456-11e4-80f3-e02c72a1d868.png)
- [x] make gridlines (next to checkbox) light gray (similar to area builder or mockup below, RGB#808080)
  ![screen shot 2014-12-15 at 12 36 53 pm](https://cloud.githubusercontent.com/assets/7852916/5442524/1157027e-8457-11e4-938d-5bcaea53441a.png)
- [x] remove the stroke around the squared residuals
- [x] The sum of squares bar should be rgb(154, 150, 255) and the squares will be the same color but remain at 40% opacity.
- [x] The best-fit sum of squares bar should be rgb(255, 52, 59) and the squares are the same color but at 40% opacity. 
- [x] The "blue" residuals should be rgb(110, 92, 231)
- [x] The "red" residuals should be rgb(178, 21, 27)
- [x] The red line colors should be (255, 0, 0) and the blue like should be (0, 0, 255)
- [x] Move the correlation readout to the left, centered under the "best-fit line" panel and centered with the graph. 
- [x] Make the sliders longer to match the latest mockup:
  ![screen shot 2014-12-15 at 12 50 10 pm](https://cloud.githubusercontent.com/assets/7852916/5442722/f2060c7e-8458-11e4-80f5-c75201aae464.png)
- [ ] Make the last tic on the graph a major tic mark (check updated table in design doc)

**Comment by veillette** [comment]
The correlation coefficient Panel has been enlarged as well. It can be easily changed back if wanted.

**Comment by veillette** [comment]
Make the last tic on the graph a major tic mark  is true except for size vs shoe size. (in dev 11).
