### ISSUE TITLE
Draggable dot on non-custom data screens

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#11]
Easily seen on multitouch devices (I've seen it on iPads and touchscreen Win7, Win8.1).
The user can drag a dot out of the box in the custom screen, then while continuing to hold their finger on the dot use a different finger to switch to one of the preset data sets. The user will still be in control of a now invisible dot. Enabling residuals makes it clear that you are controlling a dot.
Seen on 1.0.0-dev.6 & 7

Sorry the video is sideways:
https://drive.google.com/file/d/0B3HJopSo_QqLWkV1Mm1JVUFudDZXSExSSkhBWnM5X2c5c3BF/view?usp=sharing

![img_0001](https://cloud.githubusercontent.com/assets/5863899/6194333/9f724700-b380-11e4-819e-7127d3746e45.PNG)

Troubleshooting information:
Name: Least-Squares Regression
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-dev.7/least-squares-regression_en.html
Version: 1.0.0-dev.7
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
Language: en-us
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by veillette** [comment]
A dispose function was added to unlink the listeners to the dataPoints. This fixes this issue. 
The dispose function was added to the reset function (which had a similar issue)
closing
