### ISSUE TITLE
suffix on doc/ files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#15]
PhET has been using .txt (plain text) for these files, but this sim (and charges-and-fields) uses .md (markdown) files.  They do look nice when viewed in GitHub.  We should have a developer discussion about whether .md is OK.  I think it's fine for implementation-notes.txt, since they will likely be viewed by developers on GitHub.  But I'm not clear on the intended audience for model.txt - it was originally teachers, and they may not be using a reader that supports markdown.

**Comment by pixelzoom** [comment]
2/25/15 dev meeting: 

> Consensus: markdown is preferred

**Comment by veillette** [comment]
the indenting of the files was fixed. I'm going tp go ahead and close this issue.
