### ISSUE TITLE
PhetFont convenience constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#17]
I see fonts instantiated like this in LeastSquaresRegressionConstants:

> TEXT_FONT: new PhetFont( { size: 16 } )

Just wanted you to be aware that when specifying only the size, there is a convenience constructor that can be used like this:

> TEXT_FONT: new PhetFont( 16 )

The style you're using is perfectly acceptable. So whether you want to change anything or not is up to you. Feel free to close this issue without review.

**Comment by veillette** [comment]
Ok thanks for letting me know. I'll leave it as it. closing
