### ISSUE TITLE
unnecessary override of reset()

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#18]
In DataPoint, it's unnecessary to override `reset`.

``` js
    reset: function() {
      PropertySet.prototype.reset.call( this );
    },
```

For future reference, if you override a function, document with the @override annotation.

**Comment by veillette** [comment]
@jbphet explained me of the purpose of the PropertySet.prototype.reset.call( this ) and a lightbulb went off. OK I removed the reset method. Assigning to @pixelzoom  for review.
