### ISSUE TITLE
doc in DataSet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#20]
A couple questions about DataSet.

In createDataSet, the name parameter is documented like this:

> 138    @param {Object} name - {{ graphTitle: string),yAxisTitle: string ), xAxisTitle: string ),reference: string ),source: string )}

It looks like there are some extra ')' and '{' in this. Should it be this?

> 138    @param {Object} name - { graphTitle: string, yAxisTitle: string, xAxisTitle: string, reference: string , source: string }

In createDataSet, there are 2 of these comments, which don't tell me anything:

> //name: name,

Are they actual comments, or vestigial code that has been commented out?

**Comment by pixelzoom** [comment]
Moved this from #19,... When #15 is resolved, put a comment in DataSet that says something like:

> See doc/model.txt for more information.

**Comment by veillette** [comment]
The vestigial code lines have been removed and the reference to the documentation notes was added.  (this is preferable than the model.md since it is supposed to be for the teachers). Assigning to @pixelzoom for review.
