### ISSUE TITLE
points off the graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#21]
Noticed during code review #6.  When the "Height vs. Shoe Size" data set is selected, some points are off the graph. I'm not sure whether that's allowed or not, so I thought I'd mention it.   If this is expected, feel free to close.

Here's a screenshot:

![screenshot_460](https://cloud.githubusercontent.com/assets/3046552/6273579/c1834cf2-b82d-11e4-91a0-382f81249215.png)

**Comment by veillette** [comment]
Extended the vertical range to include all the dataPoints within the graph. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great, closing.
