### ISSUE TITLE
should 'x' and 'y' be translatable?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#23]
In graphing-lines, 'x' and 'y' were required to be translatable. 

>  "symbol.x": "x",
> "symbol.y": "y",

Why is that not the case for this sim? They are currently hardcoded, and appear in 2 places:

EquationNode: 'x', 'y ='
MyLineControlPanel: 'x +', 'y ='

**Comment by veillette** [comment]
forgot to tag the issue.
https://github.com/phetsims/least-squares-regression/commit/d79a365a9290e2721fab12afb334de67dbaf971b

**Comment by veillette** [comment]
The x and y symbols are now translatable. Major changes to the layout of the equation as well so best to see this fix with #25 .

**Comment by pixelzoom** [comment]
Looks good, and I will review #25 separately. Closing.
