### ISSUE TITLE
error when line is off the graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#24]
This was reported in scenery (https://github.com/phetsims/scenery/issues/387), but making an issue here too.  When if you move the 'a' and/or 'b' sliders such that the line is fully off the graph (fully clipped), then Errors are thrown. Here's the console log:

![screenshot_461](https://cloud.githubusercontent.com/assets/3046552/6274784/30031488-b837-11e4-8b87-43d506650172.png)

**Comment by veillette** [comment]
This was fixed in https://github.com/phetsims/scenery/issues/387 . @jonathanolson  did not tag his commit on it but I can confirm that it works, so closing.

**Comment by jonathanolson** [comment]
If it's helpful, it was https://github.com/phetsims/scenery/commit/dfc87c71f0bdd6098ed98f4a888d78609b35aaf2
