### ISSUE TITLE
layout of equations relies on magic numbers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#25]
EquationNode contains this TODO item, shown in context:

``` js
    // TODO: Is there a way to have less magic number for layout?
    // The layout of this equation must match the layout of another equation in MyLineControlPanel
    this.eqnPartTwoText.left = 23;
    this.eqnPartThreeText.left = 32;
    this.eqnPartFourText.left = 65;
    this.eqnPartFiveText.left = 75;
    this.eqnPartSixText.left = 87;
```

Here's EquationNode in context (top equation in the screenshot). The equation below it is created by MyLineControlPanel.

![screenshot_462](https://cloud.githubusercontent.com/assets/3046552/6307673/eb2483be-b8fa-11e4-876f-7e198e4fc7a3.png)

The problem is how to maintain horizontal layout of the elements in the 2 equations and sliders (elements of the bottom equation act as slider labels).

The above "magic numbers" approach is not going to work for other fonts, and certainly won't work if 'x' and 'y' are translated (see #23).  So I recommend reworking things so that a "relative layout" approach is used.  I'll need to take a closer look at the code to recommend the best approach, so I'll assign this to me first.

**Comment by pixelzoom** [comment]
To illustrate how the layout is flawed, here's what it looks like if 'x' is I change to 'xxx'.  It's unlikely that anyone will substitute multiple characters for 'x'. But the point is that any character that does not have the same width as 'x' in Ariel 16-point is going to have cause problems.  And that will certainly be the case in in other locales, which may use other fonts.

![screenshot_464](https://cloud.githubusercontent.com/assets/3046552/6307812/393e18ac-b8fc-11e4-8e68-a4d90dc61ee2.png)

**Comment by pixelzoom** [comment]
My recommendation on this will depend on the outcome of #29.  But I think that you'll want to have default layout metrics in EquationNode's options, which can be overridden.  And the values of those metrics in MyLineControl panel will be computed based on:
- minimum distance between the sliders, based on the width of the sliders
- maximum width of the slope and intercept, based on their min/max values and width of 'a' and 'b' strings
- width of the static pieces of the equation ('y', '=', 'x', '+')
- desired horizontal spacing/padding of equation pieces

**Comment by veillette** [comment]
I came up with a partial solution. It relies less on magic numbers and will handle change of font size or translation of the x and y strings. It is not the broadest solution you suggested: it doesn't take into account the spacing between sliders for instance, it assumes that even though 'a' and 'b' strings might be larger in translation, they wont be larger than 4 characters.

**Comment by pixelzoom** [comment]
Looks much better.  

One suggestion for improvement...The fact that values are limited to 2 decimal places is spread out, not encapsulated.  You have this in EquationNode.roundNumber:

> maxDecimalPlaces: 2

And these values with 2 decimal place in MyControlPanel:

> var equationText = new EquationNode( -0.53, -0.53 );

It would be preferable to do aways with the EquationNode constructor parameters, and promote options.maxDecimalPlaces to EquationNode's options. Or if it doesn't need to be an options (it doesn't seem to be) then use a constant.  Based on maxDecimalPlaces, EquationNode can then create it's own "max-width layout values" for slope and intercept - similar to the values that you're currently passing in to EquationNode's constructor.

**Comment by pixelzoom** [comment]
Looks much better.  

One suggestion for improvement...The fact that values are limited to 2 decimal places is spread out, not encapsulated.  You have this in EquationNode.roundNumber:

> maxDecimalPlaces: 2

And these values with 2 decimal places in MyControlPanel:

> var equationText = new EquationNode( -0.53, -0.53 );

and in BestFitLineControlPanel, the same thing:

>  var equationText = new EquationNode( -0.53, -0.53 );

This means changing (and finding!) 3 sites if you want to change the number of decimal places.

It would be preferable to do away with the EquationNode constructor parameters, and promote options.maxDecimalPlaces to EquationNode's options. Or if it doesn't need to be an option (it doesn't seem to be) then use a constant.  Based on options.maxDecimalPlaces (or constant MAX_DECIMAL_PLACES), EquationNode can then create it's own "max-width layout values" for slope and intercept - similar to the values that you're currently passing in to EquationNode's constructor.

**Comment by pixelzoom** [comment]
To compute the max width strings:

> var maxWidthSlopeString = '-0.' + _.repeat( '0', options.maxDecimalPlaces ); // eg, '-0.00'
> var maxWidthInterceptString = '-0.' + _.repeat( '0', options.maxDecimalPlaces );

**Comment by veillette** [comment]
Good idea. I couldn't get this _.repeat to work though.   My solution is a little bit less elegant.

```
   var maxWidthSlopeString = '0.';
    for ( var i = 0; i < options.maxDecimalPlaces; i++ ) {
      maxWidthSlopeString = maxWidthSlopeString + '0';
    }

    var maxWidthInterceptString = '0.';
    for ( var j = 0; j < options.maxDecimalPlaces; j++ ) {
      maxWidthInterceptString = maxWidthInterceptString + '0';
    }
```

and I removed the fake numbers from the two control  Panels.

**Comment by veillette** [comment]
In light of recent redesign tweaks (see #30) , there were additional changes to the API of Equation Node since the myLine and bestFitLine equations have different font options.  It might be worth your time to (re)review EquationNode.js

https://github.com/phetsims/least-squares-regression/blob/master/js/least-squares-regression/view/EquationNode.js

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great. Like the color coordination of the best-fit line and equation.

Closing.
