### ISSUE TITLE
positioning a node whose bounds are Bounds2.NOTHING

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#26]
DataPointNode constructor looks like this:

``` js
function DataPointNode( dataPoint, modelViewTransform ) {
    Node.call( this, { cursor: 'pointer' } );
    var self = this;

    // Move this node as the model representation moves
    dataPoint.positionProperty.link( function( position ) {
      self.center = modelViewTransform.modelToViewPosition( position );
    } );
  }
```

The problem here is that an attempt is made (`self.center =`) to position a node whose bounds are Bounds2.NOTHING (a Node with no children).  Scenery currently has a bug that is preventing this assertion from firing (see https://github.com/phetsims/scenery/issues/388). So this bug is being masked, and when scenery is fixed, this is going to fail.

DataPointNode looks like it's intended to be a base type, and not instantiated directly. Recommended to note that in the doc.  

To work around the bounds problem, provide the {Node} representation to the DataPointNode constructor, like this:

``` js
  /**
   * @param {DataPoint} dataPoint
   * @param {Node} representation
   * @param {ModelViewTransform2} modelViewTransform
   * @constructor
   */
function DataPointNode( dataPoint, representation, modelViewTransform ) {
    Node.call( this, { cursor: 'pointer' , children: [ content ] } );
    var self = this;

    // Move this node as the model representation moves
    dataPoint.positionProperty.link( function( position ) {
      self.center = modelViewTransform.modelToViewPosition( position );
    } );
  }
```

Here's how the StaticDataPointNode subtype would change. DynamicDataPointNode would use a similar approach.

``` js
function StaticDataPointNode( dataPoint, modelViewTransform ) {
    var representation = new Circle( LSRConstants.STATIC_DATA_POINT_RADIUS, {
      fill: LSRConstants.STATIC_DATA_POINT_FILL,
      stroke: LSRConstants.STATIC_DATA_POINT_STROKE,
      lineWidth: LSRConstants.STATIC_DATA_POINT_LINE_WIDTH
    } );
    DataPointNode.call( this, dataPoint, representation , modelViewTransform );
  }
```

... or feel free to inline `new Circle` and do away with `var representation` if you prefer.

**Comment by veillette** [comment]
Indeed that makes sense.  Now, DataPointNode takes an representation and parameter.   StaticDataPointNode and DynamicDataPointNode had to be adjusted accordingly. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good, closing.
