### ISSUE TITLE
use TWEEN?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#27]
Address this TODO item in DataPoint:

>  // TODO: issue #27, Would it be appropriate to use TWEEN.js here?  If not, perhaps comment that it was an option and another strategy was used

I don't have any recommendation on whether to use TWEEN, since I haven't used it yet. Best to consult with one of the other developers who has used it.  In any case, this seems like a decision that could result in significant changes, so best to address it before the sim enters the test process.

**Comment by veillette** [comment]
I have implemented the animation for the dataPoints using Tween. It does simplify somewhat the code.  There is no more step function. One of the downside of this approach though is that it is no longer possible to recapture a dataPoint  in midflight (a pretty marginal feature at best). @amanda-phet  approved the easing in of the dataPoints. Assigning to @pixelzoom  for review.

**Comment by pixelzoom** [comment]
@bereaphysics I haven't used TWEEN, so I can't really review the changes for approach or correctness. If you want someone to review it in that regard, you might try @jbphet or @samreid.  Or feel free to just close this issue, since the TODO item has been addressed.

**Comment by veillette** [comment]
@jbphet had a look at it earlier today so closing
