### ISSUE TITLE
memory leaks?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#28]
This sim calls `link` 25 times, `linkAttribute` 5 times, `multilink` 2 times, and creates 4 derived properties (`axon.DerivedProperty`).  There are also UI components (CheckBox, HSlider,..) that link to one or more axon.Property internally.

Looking at the code, it's difficult for me to determine whether observers need to be unlinked, and (if needed) when that unlinking should occur.  

There are also a few TODO items in the code:

>  LeastSquaresRegressionScreen: //TODO: is it necessary to unlink these listeners?
> RisidualLineAndSquareNode: //TODO: MEMORY LEAK ISSUE?
> SumOfSquaredResidualsChart: // TODO: memory leak?

So while I haven't profiled this sim, what I've noted above makes me suspect that this sim probably has one or more (undetected) memory leaks.

Two things are recommended:

(1) If you haven't already, profile this sim in Chrome developer tools. You may want to do this after (2), when you have a deeper understanding of what's going on.

(2) Whenever you call link (or other any function/constructor that registers an observer), document whether it needs to be unlinked. If so, where and when? If not, why not?  This will clarify (for you and others) how these dependencies are being managed. And it may reduce the need for profiling in future maintenance. Here are some examples of such documentation from reactants-products-and-leftovers:

``` js
// NumberNode: 
thisNode.numberProperty.link( thisNode.numberPropertyObserver ); // must be unlinked in dispose

// ReactionRadioButton:
// no need to unlink reactionProperty from buttons, they exist for the lifetime of the sim
var radioButton = new AquaRadioButton( reactionProperty, choice, new Text( choice.name, TEXT_OPTIONS ), RADIO_BUTTON_OPTIONS );
```

**Comment by veillette** [comment]
I have added three dispose functions to the Nodes that come and go (DataPointNode, GraphAxesNodes, and ResidualLineAndSquareNode). In addition, special attention was paid to the observable array dataPoints since many functions had position listeners. 
It certainly improved the chrome profiling, but the heap is still increasing over long time. I have only a crude understanding of chrome profiling tool. In any case it doesnt seem to slow down the sim. It is probably worth testing on the Ipad though.

**Comment by veillette** [comment]
Ok I see that garbage collection occurs on its own timewatch. Forcing garbage collection shows that plenty of things get collected so I'm doing something correct. Ok assigning to @pixelzoom  for review.

**Comment by pixelzoom** [comment]
I don't have time to do a comprehensive memory test. But did a couple of heap snapshot comparisons in Chrome, and I don't see any obvious memory leaks.  So since you seem confident that you've addressed link/unlink, I'm closing this issue.
