### ISSUE TITLE
use of white boxes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#29]
While investigating #25, these design-related questions came to mind, and could affect how we resolve #25 (equation layout).

(1) Why is the "best fit" line shown with a white box (sun.Panel) around it, like the line in the "My Line" control panel? It makes it look like a text field, sending the cue that the "best fit" line is dynamic/editable (like My Line), which it is not.

(2) Ditto for the `r = value` in the Correlation Coefficient box. This panel-within-a-panel doesn't seem to fill any purpose, and in fact sends the wrong cue that it's and editable text field.

Assigning to @bereaphysics to discuss with the designer.

**Comment by pixelzoom** [comment]
Screenshot of the UI elements in question...

![screenshot_465](https://cloud.githubusercontent.com/assets/3046552/6309781/d44c4fc4-b90d-11e4-98ab-e45d10898bd7.png)

**Comment by pixelzoom** [comment]
Also wondering about the "My Line" equation. The slope and intercept values are editable, other parts of the equation are not. And you want to tie this equation to the one below it. Why make the entire equation look like a text field? Why not put white boxes around just the editable parts?

What it looks like now:

![screenshot_466](https://cloud.githubusercontent.com/assets/3046552/6309824/21743afa-b90e-11e4-900c-c7c29b52b99f.png)

This look sends a clearer message about what is editable, strengths the association between a & b symbols and values, simplifies equation layout, and makes the equation look cleaner overall:

![revised](https://cloud.githubusercontent.com/assets/3046552/6309950/44541c2e-b90f-11e4-94db-01e74b64816b.png)

Perhaps the sign on the intercept is an issue?...

**Comment by veillette** [comment]
I'll bring it up to the design team.  The coefficient of correlation used to be its own panel. Much later on it was wrapped around an accordion box so that it can be hidden but it was left with the white box.. So we may need to revisit this.

**Comment by pixelzoom** [comment]
If sign of intercept is an issue, you could do this:

![screenshot_467](https://cloud.githubusercontent.com/assets/3046552/6310058/5ed62208-b910-11e4-94de-4b71de24ced6.png)

**Comment by pixelzoom** [comment]
If sign of the intercept is an issue, it could look like this:

![revised2](https://cloud.githubusercontent.com/assets/3046552/6310074/766c22c8-b910-11e4-8075-8f1fc0dc8cc6.png)

**Comment by amanda-phet** [comment]
I think the readout that was used in Beer's Law Lab will work here. 
![screen shot 2015-02-25 at 4 58 19 pm](https://cloud.githubusercontent.com/assets/7852916/6383618/b53ef7c0-bd0f-11e4-8b93-f85e80662736.png)

We want the readout to stand out, but not look editable, so I think something as simple as a gray stroke (rather than black) will work here:
![screen shot 2015-02-25 at 4 59 52 pm](https://cloud.githubusercontent.com/assets/7852916/6383623/c36088f0-bd0f-11e4-956c-67932b441e0d.png)

**Comment by veillette** [comment]
It was decided to go with the white panels with the gray stroke so I'm closing this tissue.
