### ISSUE TITLE
New design tweaks (based on dev version 11)

### ISSUE THREAD

**Issue by veillette** [phetsims/least-squares-regression#30]
- [x] use a gray stroke around  the three white boxes in the control panel. use rgb(204,204,204).
- [x] keep Best Fit Line title at all times in control panel
- [x] make slope and intercept values bold in My Line Equation (for numbers).
- [x] make entire  Best Fit Line Equation red, no bold, using the same color as the best fit line on graph
- [x] move up  button box in correlation coefficient panel
- [x] have numbers from 1 to 10 have 2 numbers after the decimal.

**Comment by veillette** [comment]
It is not possible to move up the buttonBoxin the correlation coefficient panel.  AccordionBox (a common code component) has this wired.

```
 // button & title layout
    this.expandCollapseButton.centerY = options.titleNode.centerY = collapsedBox.centerY;
```

**Comment by pixelzoom** [comment]
> It is not possible to move up the buttonBox

I'm not clear on what you're trying to do. Can you describe, or show a mockup?

**Comment by pixelzoom** [comment]
@bereaphysics said:

> It is not possible to move up the buttonBox

I'm not clear on what you're trying to do. Can you describe, or show a mockup?

**Comment by pixelzoom** [comment]
If you're trying to align the tops of the expand/collapse button and the 'Correlation Coefficient' title, we could add this option to AccordionBox:

> titleAlignY: 'center' // vertical alignment of button and title, 'top'|'bottom'|'center'

...but it's something that I would push back on.

**Comment by veillette** [comment]
Correct, the design team wanted to align by the tops of the title and expanded/collapse button.

**Comment by veillette** [comment]
This is an unusual situation since the title uses multiline. This is not something that is likely to come up again.

**Comment by pixelzoom** [comment]
I estimate that it would take 15-30 minutes to add options.titleAlignY to AccordionBox. I had proposed values 'top'|'bottom'|'center'.  But I can't imagine 'bottom' ever being desirable.

**Comment by veillette** [comment]
If you are willing to implement it. You will have the first test case in LSR.

**Comment by pixelzoom** [comment]
@bereaphysics I added titleAlignY to AccordionBox, and set it to 'top' for the 'Correlation Coefficient' accordion box.

**Comment by veillette** [comment]
Looks good, this will please @amanda-phet . Closing.
