### ISSUE TITLE
custom data set is cleared when switching to some other data set

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#31]
When you switch to one of the preset data sets, your custom data set is automatically cleared. This makes it difficult to compare your custom data-set to any of the other 'preset' data sets. And since there is an eraser button next to the bucket, I'm not sure why it's desirable to clear the custom data set. 

Steps to reproduce:
1. Start the sim. 'Custom' will be selected in the combo box.
2. Drag some points from the bucket to the graph.
3. Switch to something else in the combo box (e.g., 'Height vs Shoe Size').
4. Switch back to 'Custom' in the combo box. The points that you placed previously are no longer on the graph.

**Comment by veillette** [comment]
@amanda-phet agreed that the custom data set should not be cleared.

**Comment by veillette** [comment]
Assigning to @pixelzoom for code review. 

We will need to have the QA team look at this feature since it may impact performance if the number of dataPoints is large, it might take a significant time to get back to CUSTOM.

**Comment by pixelzoom** [comment]
Works great, closing.
