### ISSUE TITLE
Source and reference dialogue box grammar

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#32]
@bereaphysics is already aware of these and I believe the fix has already occurred. In 1.0.0-dev.13 there are a couple things to be changed.
1. In the four Temperature (F and C) vs. Longitude/Latitude data sets, the dialogue reads "Average January temperature in fifty major US compared to their longitudes/latitudes" where the word "cities" needs to be added between "US compared".
2. I caught three data sets missing periods at the end of their description:
   Height vs. Shoe Size
   Minimum Wage Over Time
   Orbital Speed vs. Distance from Sun
3. This point is more of a question, but should the four sets that read "___ Over Time" in their title be replaced with "___ vs. Time" to appeal to consistency with the other ten data sets?

**Comment by veillette** [comment]
I addressed the first two issues in this commit https://github.com/phetsims/least-squares-regression/commit/98b3a76a1b88b29743849a60c53d85c5b7dfa942

**Comment by veillette** [comment]
Assigning the third point to @amanda-phet .

**Comment by amanda-phet** [comment]
I think that is a good idea. Thanks @phet-steele for the suggestion and attention to detail!

**Comment by veillette** [comment]
Done. Closing.
