### ISSUE TITLE
Switching between data sets could be "snappier" 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/least-squares-regression#34]
Currently in RC.1 switching between data sets on the iPad is a bit slow (fair bit of delay, especially when switching back to the custom mode if many custom data points were placed).

Otherwise, the sim runs very smoothly.

@bereaphysics will talk with @jonathanolson to see if there is an easy way to improve this performance.

**Comment by samreid** [comment]
Here's a bird's-eye view of where the time is being spent:

![image](https://cloud.githubusercontent.com/assets/679486/6623286/b2de886c-c8a7-11e4-8e92-492564a7afb6.png)

**Comment by ariel-phet** [comment]
@jonathanolson said he would take a look to see if some optimization can occur

**Comment by veillette** [comment]
Forgot to tag this last commit
https://github.com/phetsims/least-squares-regression/commit/90c903c2f4cb8194581887018d8d3a687c43588e

**Comment by veillette** [comment]
It is definitely speedier. It will need some regression testing before moving ahead. I'll assign to @ariel-phet for review.

**Comment by ariel-phet** [comment]
I looked at this issue with @bereaphysics, it seems like performance is now acceptable on iPad2
