### ISSUE TITLE
Dragging from bucket body ideally should pull data point out

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/least-squares-regression#35]
In sims with buckets, I've been used to mouse-downs on the bucket OR particles dragging a particle out, and I think it's more usable.

**Comment by ariel-phet** [comment]
@amanda-phet - please make the call if you think this would be OK. I generally agree it makes the sim more usable (basically anywhere you grab on the bucket with touch or mouse grabs a particle for you)

**Comment by amanda-phet** [comment]
I am definitely OK with it! I got used to aiming my cursor for the orange pile but I agree that anywhere in the bucket makes sense.

**Comment by veillette** [comment]
implemenetd and tested by @phet-steel in version 1.0.0.dev14.
closing
