### ISSUE TITLE
Layering of "sum bar" over axis arrow

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/least-squares-regression#36]
@bereaphysics, this is a pretty minor point, but it looks like when the sum bar extends to its maximum it covers the top half of the x-axis arrowhead. See below. I thin it would be better if the full arrowhead were still visible. 

![capture](https://cloud.githubusercontent.com/assets/4051174/6787188/c133a886-d156-11e4-9829-68c25df6f1a2.PNG)

**Comment by veillette** [comment]
On the z-order, the arrow head has been put on top of the barrometer
