### ISSUE TITLE
Sum of squares indicator not resetting properly

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/least-squares-regression#37]
This bug does not seem to be platform specific. 

To reproduce:
1. Open the sim in its default state
2. Place several points in the play area (not in a straight line)
3. Press the Reset All button
4. Turn on the "Squared Residuals" check box in both the best-fit and my line panels

Even though no points are present, and no "r" is shown, the indicator for the sum have no reset to zero

![capture2](https://cloud.githubusercontent.com/assets/4051174/6787590/6e6040ee-d159-11e4-9494-47d88e6ebeb6.PNG)

**Comment by orejolaphet** [comment]
Occurs  in OSX 10.9.2 Safari 7.0.5 & Win 7 IE 10

**Comment by veillette** [comment]
the sum of squared residuals has a reset function that can be called from the resetAll button
