### ISSUE TITLE
My line slope slider lags

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/least-squares-regression#38]
Test device: Macbook Pro
Operating System: OSX 10.10.2 (Yosemite)
Browser: Firefox 
Problem description: When using the "height vs. shoe size" data set, and My Line and Squared Residuals are checked, the slider that controls slope lags a bit and then jumps to catch up.  
Steps to reproduce: Open "height vs. shoe size" and click Squared Residuals. Drag the slope slider. 
Severity: low-medium

Troubleshooting information (do not edit):
Name: Least-Squares Regression
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-rc.2/least-squares-regression_en.html
Version: 1.0.0-rc.2
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0
Language: en-US
Window: 1081x583
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by veillette** [comment]
I'm punting on this one since it affects only one particular data sets. The reason for the slow performance is that this data sets contains a lot of dataPoints and therefore there are a lot of line residuals and square residuals to render.

**Comment by amanda-phet** [comment]
Sounds good. Closing.
