### ISSUE TITLE
You can drag a point from different places on that point

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/least-squares-regression#39]
I noticed that sometimes it was difficult to precisely place a point because my cursor (the hand) was covering the point. After many trials, I realize that you can grab a point from the center or anywhere around the circumference, which will impact the position of the hand and the point. 

Is the only way to change this to have every point jump up above your cursor/finger? Should we do this? I'm OK with the current behavior, but it can get annoying if you're trying to be precise (and I assume most users won't).

**Comment by veillette** [comment]
Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks great!
