### ISSUE TITLE
Small tweaks to make

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/least-squares-regression#4]
- [x] Add a space after "Source:" in popup dialog box 
- [x] Change the title to "Least-Squares Regression" (add hyphen)
- [x] Remove axes labels on Custom data set so that they do not display "X" and "Y"
- [x] Remove "Best-fit Line" title when that panel is expanded
- [x] Remove leg stride data set
- [x] Edit some incorrect axes labels: Life Expectancy (years), Mean Orbital Speed (km/s), Distance from Sun (AU), Height (in), Shoe Size (US)
- [ ] When you add in the unit toggle we can determine which units to toggle

**Comment by veillette** [comment]
See https://github.com/phetsims/least-squares-regression/commit/1ca386b36ce6d4fa120496393e4a92748ebabed1 for some of the changes

**Comment by veillette** [comment]
It was decided not to use a unit toggle. closing
