### ISSUE TITLE
Issue "?stringTest=double" covering buttons

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/least-squares-regression#43]
Testing for task https://github.com/phetsims/tasks/issues/245
Menu drop down arrows are covered
![screen shot 2015-05-26 at 1 55 17 pm](https://cloud.githubusercontent.com/assets/5631059/7821915/38eb5024-03af-11e5-9a09-0b80b3c1c4c6.png)

**Comment by pixelzoom** [comment]
Duplicate of #49.
