### ISSUE TITLE
Usage of @private addTick in HSlider

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/least-squares-regression#47]
In https://github.com/phetsims/least-squares-regression/commit/8b38a863c1dd783dbad9f78feb72c373c8eeb84a, in order to fix the startup error, I had to point addTick (@private) to majorTicksParent (@private), so they'll both need to be fixed.

May require adding another type of tick to do what is being accomplished.

**Comment by jessegreenberg** [comment]
Since HSlider does not support ticks that are centered vertically on the track, we can add our own tick nodes to `verticalSlider` to support this without calling on @private functions and variables.

**Comment by jessegreenberg** [comment]
Done in commit above, closing.
