### ISSUE TITLE
?stringTest=Double expands panels over graph area

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#49]
With ?stringTest-double, the panels on either side expand into the graph area and are layered underneath points, lines, and squared residuals. The drop-down menu aslo expands drastically, and the whole sim gets quite unusable with ?stringTest=long.

![lsr dub](https://cloud.githubusercontent.com/assets/5863899/12488369/73c62490-c028-11e5-9be8-a8b92b3d770e.PNG)

Tested on phettest with Win 8.1 FF. For phetsims/tasks/issues/479

Troubleshooting information:
Name: ‪Least-Squares Regression‬:‪Least-Squares Regression‬
URL: http://phettest.colorado.edu/least-squares-regression/least-squares-regression_en.html?ea&brand=phet&stringTest=double
Version: 1.0.0-dev.14 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Layout with stringTest=double and stringTest=long is looking nice now:

![layout](https://cloud.githubusercontent.com/assets/6396244/13655899/00004194-e620-11e5-9c6e-5c4c25983f2a.PNG)

Closing.  If any i18n layout problems come out of RC testing, new issues can be created.
