### ISSUE TITLE
Keep the checkboxes in their current state when switching between data sets

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/least-squares-regression#5]
I noticed in interviews that if a student wanted to compare best-fit lines or the sums of the squared residuals between data sets, they would need to re-check the checkboxes that they had checked before. (The sim essentially resets upon selecting a new data set.) 

I would like to change this behavior so that any checkboxes remain checked when switching between data sets.

**Comment by veillette** [comment]
This is relatively easy to do
I can stop resetting the entire propertySet upon a change of DataSet. This has the unattended consequence of leaving the sliders in the same position though. Let me know if you prefer to reset the sliders and I can cherry pick which property to reset/not reset.

**Comment by veillette** [comment]
Closing this after the review meeting
