### ISSUE TITLE
Best Fit line doesn't update with points on edges of graph

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#52]
If you slowly edge a point onto the graph, there is a small area around the border in which you could place the point without the best fit line representation updating. Grabbing another point, or switching to a data set and back, will then properly update the line. "My Line" behaves just fine.

![lsr01](https://cloud.githubusercontent.com/assets/5863899/13794205/57110eba-eac0-11e5-9a1a-27c1fc215963.gif)

Seen in live version as well, on Win 10 browsers. For phetsims/tasks/issues/542.

Troubleshooting information:
Name: ‪Least-Squares Regression‬
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-rc.1/least-squares-regression_en.html
Version: 1.1.0-rc.1 2016-03-11 02:08:11 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"9c243fba","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"least-squares-regression":{"sha":"a4164ebe","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Residuals update correctly.  It is only the best fit line that is delayed.

![capture](https://cloud.githubusercontent.com/assets/6396244/13992094/4c8f48c8-f0e0-11e5-9395-7d5965498ab3.PNG)

**Comment by jessegreenberg** [comment]
updateBestFitLine is called every time data point position changes.  Perhaps linear fit params are not being updated at the right time.

**Comment by jessegreenberg** [comment]
Ah, when the data point is added to the graph the best fit line is updated before the graph points and residuals.

**Comment by jessegreenberg** [comment]
Fixed in commit above, to be verified in next RC.

**Comment by phet-steele** [comment]
@jessegreenberg visually, yes, this issue is resolved in 1.1.0-rc.2. However, computationally the sim still fails to update with edge points. Specifically the best-fit line equation, squared residuals sum, and correlation coefficient fail to update.

**Comment by jessegreenberg** [comment]
The control panel readouts should now update at the correct time.

**Comment by phet-steele** [comment]
They do.
