### ISSUE TITLE
We shouldn't translate credited sources

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#53]
@ariel-phet @jessegreenberg the sim currently contains strings that, in my opinion, should not be translated. These strings would be any with a string key ending in ".source" and are used to credit the source of a data set like this:
![lsrsource](https://cloud.githubusercontent.com/assets/5863899/13820605/c267801a-eb63-11e5-87a5-92b8856613b2.PNG)

I'd imagine it would still be okay to translate the "Source" string with string key "source" (without the dot). For phetsims/tasks/issues/542.

**Comment by ariel-phet** [comment]
@phet-steele good point.

@jessegreenberg probably best to make sure the actual source reference is not translatable.

**Comment by jessegreenberg** [comment]
Good catch @phet-steele.  Fixed in the above commit, to be verified in next RC.

**Comment by phet-steele** [comment]
Source strings are not in the strings JSON file anymore, so I'd say this is fixed in 1.1.0-rc.2.
