### ISSUE TITLE
Proposed change to "Source" string

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#54]
Currently the sim displays its source dialogue for data sets with these string keys (in a super simplified Steele friendly way):

source + colonPunctuation + *.source

which would look like:

Source: Some sort of source et al. (1994)

@jessegreenberg the first proposed change I have is to get rid of the colonPunctuation key (with value ": ") and just put the colon into the value of the source string key (changing value from "Source" to "Source: ").
The second proposed change is to make this whole thing a pattern to accommodate rtl. So change the source string key to a pattern with a value like:

Source: {0}

where the {0} is the *.source string key for that particular data set. @ariel-phet @jessegreenberg thoughts? I wouldn't know how hard or easy the second change is, but I'd think the first change is trivial. For phetsims/tasks/issues/542

**Comment by jessegreenberg** [comment]
Good catch @phet-steele!  Yes, `Source: {0}` would be much better here.

That change would be trivial, and will be done for the next RC.

**Comment by jessegreenberg** [comment]
Done in commit above, to be verified as fixed in next RC.

**Comment by phet-steele** [comment]
Pattern is working as expected in 1.1.0-rc.2.
