### ISSUE TITLE
Extra space in string value

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#55]
@jessegreenberg how much of a nit-picky perfectionist can I be? This much:

![lsrheight](https://cloud.githubusercontent.com/assets/5863899/13822635/0835ad9e-eb6c-11e5-86aa-e4c8c212976f.PNG)

There is an extra space before the value of 'heightShoe.yAxisTitle', can you get rid of it :smile:? I doubt it's there for a reason.

**Comment by jessegreenberg** [comment]
Part of https://github.com/phetsims/tasks/issues/542.

Good catch @phet-steele!
