### ISSUE TITLE
Residual Lines Disappear

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/least-squares-regression#56]
Related to https://github.com/phetsims/tasks/issues/542
Test device: Win 7 Laptop, Bates

Operating System: Win 7 64-bit

Browser: IE 11.0.9600.18230

Problem description: The residual lines disappear after box is clicked.

Steps to reproduce: Select Residuals check box. Lines will disappear once mouse is moved. 

Severity:

Screenshots:
![residuals ie](https://cloud.githubusercontent.com/assets/12610678/14085506/796a2286-f4dd-11e5-91f8-478e9871ab22.JPG)

Troubleshooting information (do not edit):

Name: ‪Least-Squares Regression‬

URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-rc.1/least-squares-regression_en.html

Version: 1.1.0-rc.1 2016-03-11 02:08:11 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Language: en-US

Window: 1366x674

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"9c243fba","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"least-squares-regression":{"sha":"a4164ebe","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@jessegreenberg this one may be something specific to that device, maybe hardware or maybe screen size/resolution. Resizing the browser window on the reported device (Bates) no longer presents this problem. Trying IE11 on different devices with different resolutions also does not present this problem.

**Comment by phet-steele** [comment]
The residuals disappear when the cursor changes from a hand back to a pointer.

**Comment by jessegreenberg** [comment]
Very strange, @phet-steele are you able to reproduce this with Bates (or any machine) with the deployed version of the sim?

Either way, given the comment https://github.com/phetsims/least-squares-regression/issues/56#issuecomment-202584548, I am inclined to mark as `wontfix`.  @ariel-phet do you agree?

**Comment by ariel-phet** [comment]
I agree, tried to reproduce on my home machine, no dice. Seems pretty computer specific in that case (and IE is a small user share for us these days).
