### ISSUE TITLE
Best fit line residual behavior with undefined slope

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/least-squares-regression#57]
@phet-steele recently pointed this out to me.  There is some varying behavior for the best fit residuals and correlation coefficient when the slope of the best fit line is undefined.  When the best fit line slope is undefined, the best fit line is invisible, but the residuals are still visible.
![capture](https://cloud.githubusercontent.com/assets/6396244/14092506/9d3920c8-f504-11e5-9edc-dff4e045154d.PNG)

Also, sometimes we are able to see 'NaN' as the correlation coefficient instead of a blank readout.
![nan](https://cloud.githubusercontent.com/assets/6396244/14092530/d004be0e-f504-11e5-9341-1fa00d71a2cb.PNG)

@phet-steele if I described anything incorrectly, please let me know.

@ariel-phet and @amanda-phet are these issues that should be fixed, or was this the intended behavior?  These can also be observed in the released version of the sim.

**Comment by ariel-phet** [comment]
@jessegreenberg I think this is an issue that generally does not need to be addressed. It is tough to imagine a meaningful data set where the only data appears at one dependent variable value with multiple points at that one dependent value.

However, I would change the correlation coefficient to just be blank instead of NaN

Basically things about a data fit should get whacky if you only an undefined slope for your best fit line.

**Comment by jessegreenberg** [comment]
Looks like the denominator is coming up NaN in getPearsonCoefficientCorrelation of PearsonCorrelationCoefficientNode.js.

**Comment by jessegreenberg** [comment]
Somehow we are trying to take the square root of a negative number in getPearsonCoefficientCorrelation.

**Comment by jessegreenberg** [comment]
Fixed, `NaN` should not be visible in this case.  Closing.

**Comment by phet-steele** [comment]
@jessegreenberg can we also make the sim not show residuals and squared residuals (for the best-ft line) in the scenario of your first screenshot? In other words, when r is null.

**Comment by jessegreenberg** [comment]
Sure, has been done.  Leaving open to be verified as fixed in the next RC.

**Comment by phet-steele** [comment]
Verified fixed..
