### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#6]
Do this after dev testing. @bereaphysics, please let me know when it's ready, and assign back to me.

**Comment by veillette** [comment]
Assigning to @pixelzoom for code review.

**Comment by pixelzoom** [comment]
A few trivial commits that I made while doing the review:
https://github.com/phetsims/least-squares-regression/commit/4e597a319a8ef2dc5ac2a02a26cce6912f4c26a0
https://github.com/phetsims/least-squares-regression/commit/78fb4886f9267e2a7f6305f7f1c8572ae4c246f1
https://github.com/phetsims/least-squares-regression/commit/344b62ec7feacb9443a3a374ebed25b4db9121fb

**Comment by pixelzoom** [comment]
I've completed the code review. Overall, the code is in excellent shape - very easy to read, well organized, well documented (well done!). I've created a few issues, all labeled as `code review`.  I've assigned #25 to myself, to come up with a recommendation. The others are assigned to @bereaphysics.  Let me know if you have any questions.

**Comment by veillette** [comment]
Thanks @pixelzoom.

**Comment by pixelzoom** [comment]
All issues labeled `code review` have been addressed. Closing.
