### ISSUE TITLE
r for horizontal line 

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/least-squares-regression#63]
Related to https://github.com/phetsims/tasks/issues/576

Test device: Mac, Dirac 

Operating System: OS X 10.9.5

Browser: Safari 9.0 (9537.86.1.56.2)

Problem description: The r value for a horizontal line will show as blank (undefined), +0, or -0. It seems from @jessegreenberg in https://github.com/phetsims/least-squares-regression/issues/62 that it should always be undefined. 

Steps to reproduce: To get +0 or -0, adjust custom line until slope of 0 is achieved. To get undefined, start fresh and place two dots on the screen in a way that has slope zero. 

Severity:

Screenshots: 
![screen shot 2016-04-13 at 11 27 46 am](https://cloud.githubusercontent.com/assets/12610678/14503110/c6d6dc4a-016b-11e6-9418-0c7b0b62d9f4.png)
![screen shot 2016-04-13 at 11 27 30 am](https://cloud.githubusercontent.com/assets/12610678/14503108/c6d54cae-016b-11e6-9722-ea35461d849d.png)
![screen shot 2016-04-13 at 11 35 42 am](https://cloud.githubusercontent.com/assets/12610678/14503151/ea7c3fd2-016b-11e6-8fe3-ef7a1621868b.png)

Troubleshooting information (do not edit):
Name: ‪Least-Squares Regression‬
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-rc.3/least-squares-regression_en.html
Version: 1.1.0-rc.3 2016-04-13 00:18:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/537.86.1
Language: en-us
Window: 1240x620
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.24.17)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"4c84154a","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"least-squares-regression":{"sha":"ee984721","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
I believe this is the intended behavior.  For 

`r = ∑((X - My)(Y - Mx)) / √((SSx)(SSy))`  Where `(SSx)  = ∑(X - Mx)^2`and `SSy = ∑(Y - My)^2`,

`√((SSx)(SSy))` equates to zero when the points are all perfectly horizontal, so r = NaN, as in the first image from  https://github.com/phetsims/least-squares-regression/issues/62#issuecomment-209556082.  But `√((SSx)(SSy))` is non zero for the last two images in https://github.com/phetsims/least-squares-regression/issues/62#issuecomment-209556082, so we have `0/someValue`.  @ariel-phet can you verify that this is correct?

**Comment by jessegreenberg** [comment]
@ariel-phet would you mind reviewing this issue and behavior before I publish the next RC?

**Comment by ariel-phet** [comment]
The behavior seems correct and acceptable to me.

For just 2 points, 2 points will always be on a line, so if that line's slope happens to be zero, the correlation is undefined.

If multiple points are on a zero slope line (a horizontal line), the correlation is basically zero (one value is completely not affecting the other). For example if you were plotting the value of the speed in light in vacuum vs the population of the world, the speed of light would remain constant, and would be completely uncorrelated to population, as it should be.
