### ISSUE TITLE
Sum bar for My Line doesn't update immediately

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/least-squares-regression#64]
Test device: Schrodinger

Operating System: Windows 8

Browser: Chrome

Problem description: The sum bar under My Line remains blank after points are added to the graph until one of the sliders is dragged. Also, if you add more points onto the graph after updating the first time, it still won't update for those new points until adjusted again.

Steps to reproduce: In custom, check My Line, and adjust it to any values where it is visible, and check Residuals and Squared Residuals, then drag some points onto the graph. The shaded squares will appear, but the sum bar will not show any value. Then change one of the sliders for the line and only then will the sum bar show anything. If you then add more points, the line must be adjusted again for the bar to update for the new points.

Screenshots: 
![lsr 1](https://cloud.githubusercontent.com/assets/11947677/14502983/2e4ffc54-016b-11e6-8e5a-1185cb84abe8.PNG)
![lsr 2](https://cloud.githubusercontent.com/assets/11947677/14502989/33008480-016b-11e6-9f99-5a6ecc33f14c.PNG)

Troubleshooting information (do not edit):
Name: ‪Least-Squares Regression‬
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.0-rc.3/least-squares-regression_en.html
Version: 1.1.0-rc.3 2016-04-13 00:18:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Language: en-US
Window: 1920x973
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"4c84154a","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"least-squares-regression":{"sha":"ee984721","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

For phetsims/tasks#576

**Comment by jessegreenberg** [comment]
Yikes, good catch @brroberts1231.  This should be fixed in the above commit.

**Comment by phet-steele** [comment]
Fixed in 1.1.0-rc.4, thanks @jessegreenberg @brroberts1231.
