### ISSUE TITLE
User reported issue: x-axis for US gas price vs time

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/least-squares-regression#68]
> Ps.:  I have checked the number of data points.
> gasolineYear.xAxisTitle Years Since 1976
> should be changed to
> gasolineYear.xAxisTitle Years Since 1979

**Comment by oliver-phet** [comment]
@amanda-phet Can you verify it should be 1979? Then we can have someone do a maintenance release?

**Comment by amanda-phet** [comment]
You're correct. It should be 1979. There was a typo in the design doc!

**Comment by veillette** [comment]
This was corrected in the sim.

**Comment by oliver-phet** [comment]
@phetsims/martin let me know when this is published and I can contact the user.
