### ISSUE TITLE
Overlapped points cause them to detach from residuals

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#74]
1. Place at least three points on the graph where two points are basically entirely overlapping.
2. Switch to a preset (so leave Custom).
3. Switch back to Custom.
4. Turn on Residuals and Squared Residuals.
4. Drag the point that isn't involved in the overlap. It will be detached from its residuals. (no errors thrown)

![lsr01](https://user-images.githubusercontent.com/5863899/31290743-d76716b4-aa8a-11e7-8dc4-0610f58bc172.gif)

**Comment by samreid** [comment]
Maybe related to #93

**Comment by samreid** [comment]
@Nancy-Salpepi can you please see if this was fixed as part of #93? Close if ok.

**Comment by Nancy-Salpepi** [comment]
Holding off on verifying this until #93 is fully fixed.

**Comment by Nancy-Salpepi** [comment]
This looks good too! Closing.
