### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/least-squares-regression#79]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Overlap of pointer areas for residuals and squared residuals
* These can sometimes be hard to press as well

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56156890-69abe580-5f7b-11e9-920c-353b6bfec839.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56156891-69abe580-5f7b-11e9-85c7-7edd8bd902f2.png)

**Comment by amanda-phet** [comment]
Should the pointer areas for checkboxes be refined so that they don't overlap?

**Comment by samreid** [comment]
After the commit:

<img width="1626" alt="image" src="https://github.com/user-attachments/assets/0c9b44fb-49be-41bd-a5d1-85ee7593afad" />

@KatieWoe or @amanda-phet does this seem OK? Any other recommendations in this area?

**Comment by KatieWoe** [comment]
Image looks ok to me

**Comment by samreid** [comment]
Thanks, this issue seems good to close, but feel free to reopen if there's more in the future.
