### ISSUE TITLE
Squared Residuals Layering

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#8]
If enough squares overlap in one area, they can cover both lines and residuals, and grid lines. The screenshots are a more extreme case with many dots, but the opacity starts to increase quickly just after a few.
![orphan dots](https://cloud.githubusercontent.com/assets/5863899/6153887/00f46758-b1e5-11e4-9db7-4ec62b3b1b17.png)

Any newly dragged dots will have their residuals layered above the squared residuals.
![orphan lines](https://cloud.githubusercontent.com/assets/5863899/6154089/3d5b4ca6-b1e6-11e4-9105-1acc1f67e951.png)

Happens on all Win 8.1 browsers in 1.0.0-dev.6

Troubleshooting information:
Name: Least-Squares Regression
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-dev.6/least-squares-regression_en.html
Version: 1.0.0-dev.6
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by veillette** [comment]
This can be solved by having the lines be on top of the squares. This will be addressed in #13. closing.

**Comment by veillette** [comment]
Reopening. even though the lines are on top it can look very busy. I'm opened to explore other options.

**Comment by jessegreenberg** [comment]
This is more of a design question, and can be investigated after the redeploy.  I am unfamiliar with design considerations for this sim.  Perhaps we could investigate limiting the opacity of layered squares.  That would have some performance implications, and I am not sure if that is supported.  Will look into it briefly.

Perhaps there is a pedagogical reason for increasing the opacity as squares are layered.

**Comment by jessegreenberg** [comment]
> Perhaps we could investigate limiting the opacity of layered squares. 

This isn't supported and it would have some performance implications.

Another options would be to have a single rectangle over the graph area that gets updates to visible sections.  But this is also very difficult to do without constructive area geometry.

**Comment by samreid** [comment]
@amanda-phet can you please recommend how to proceed for this issue?

**Comment by amanda-phet** [comment]
I don't think this is a scenario that needs fixing. The transparency behavior works really well, and it takes many squares to effectively cover another points residual. There isn't a pedagogical reason to layer the points like this and have a line so far away that the squares are this large. So I think we should close this.
