### ISSUE TITLE
the '\n' in the Correlation Coefficient translation is not working 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/least-squares-regression#80]
The PhET Translation Utility for the Least-Square Regression Strings uses several '\n' in the text that works very well for the ones in the dialog texts. For example for Temperature (˚F) vs. Latitude:

![Screen Shot 2020-06-22 at 1 20 49 PM](https://user-images.githubusercontent.com/26031501/85322116-653a6100-b48b-11ea-8a33-623e1fde606c.png)
![Screen Shot 2020-06-22 at 1 21 04 PM](https://user-images.githubusercontent.com/26031501/85322122-67042480-b48b-11ea-924f-82e6e27e22e9.png)

But it doesn't work for the translation of 'Correlation\nCoefficient':
![Screen Shot 2020-06-22 at 1 23 33 PM](https://user-images.githubusercontent.com/26031501/85322279-b0ed0a80-b48b-11ea-8c20-8f61f3f32660.png)
![Screen Shot 2020-06-22 at 1 23 44 PM](https://user-images.githubusercontent.com/26031501/85322286-b34f6480-b48b-11ea-9818-fce374d1394d.png)

I already try to separate the '\n' from the words of the translation, but it didn't work. 
 
I guess that the problem is that the string is in a different type of component.

**Comment by veillette** [comment]
Very curious.
I could not reproduce on master.

Currently we have on master `PearsonCorrelationCoefficientsNode.js`  

```js
 titleNode: new RichText( LeastSquaresRegressionStrings.correlationCoefficient, {
        replaceNewlines: true,
        align: 'center',
        font: LeastSquaresRegressionConstants.TEXT_BOLD_FONT,
        maxWidth: MAX_LABEL_WIDTH
      } ),
```

I'll note that MultilineText was replaced by Rich Text on 3/8/2023 (see https://github.com/phetsims/scenery/issues/1542) so maybe that explains why I can not reproduce it.
