### ISSUE TITLE
SceneryPhet/GridCheckbox should be leveraged

### ISSUE THREAD

**Issue by veillette** [phetsims/least-squares-regression#83]
The GridIcon and its invocation in a checkbox should be replaced by the common code GridCheckbox.
Discovered while working on https://github.com/phetsims/scenery-phet/issues/777

**Comment by veillette** [comment]
In order to use the Scenery-Phet gridcheckBox, I has to adjust the gridSize and gridStroke to match the least-squares-regression grid Icon. 
````
    // Create grid checkbox with grid icon
    const gridCheckbox = new GridCheckbox( model.showGridProperty, {
      gridSize: 48,
      gridStroke: LeastSquaresRegressionConstants.MAJOR_GRID_STROKE_COLOR
    } );
````

Making a visual comparison: 

Using SceneryPhet/GridCheckBox 
![Least-Squares Regression screenshot (2)](https://user-images.githubusercontent.com/7633344/195840158-c2ae129b-2660-4b31-9884-8026ef9f82c4.png)



Using Least-Squares-Regression/GridIcon
![Least-Squares Regression screenshot (3)](https://user-images.githubusercontent.com/7633344/195840265-a561af53-259e-4d2d-8b58-1665d4c3bc66.png)


One can notice a slight offset between the spacing of the checkbox and the grid icon.

Assigning to @amanda-phet  to approve of the visual change.

**Comment by amanda-phet** [comment]
@veillette this looks totally fine to me. 

Could we see if the default GridCheckbox is adequate? I looked at two sims that use GridCheckbox (I think) and it looks pretty similar to this one. Was the main difference the stroke color? If so, maybe we should stick with the default color, for consistency between sims?

**Comment by veillette** [comment]
The main difference is the stroke color and the size (it is quite a  bit larger than the default, 48 instead of 30).
The default color is rgb( 100, 100, 100 ) for the gridCheckBox but least squares regression uses rgb( 128, 128, 128 ). 
However, that very same color is also used for the major grid stroke on the graph. I don't know if that affects your decision.

I included screenshots (with a portion of the graph with major stroke) for ease of comparison

With LSR size and color
![image](https://user-images.githubusercontent.com/7633344/196705139-d218674b-c6dd-4ae7-81a6-53da7815e68c.png)


with LSR size but gridcheckbox default color 
![image](https://user-images.githubusercontent.com/7633344/196705571-548638c9-6cc5-45ef-9d36-5e3db9e72c82.png)


with gridcheckbox default color and size 
![image](https://user-images.githubusercontent.com/7633344/196706436-f3904c23-8bc5-45ea-ba27-49e2697724c0.png)


Let me know what you think. @amanda-phet

**Comment by amanda-phet** [comment]
I think this can be closed!
