### ISSUE TITLE
Boxes open instead of closed by default

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/least-squares-regression#89]
**Test device**
Lenovo
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1190.
When comparing the dev version to the published version, the Best Fit Line box and Correlation Coefficient box are both open by default instead of closed by default now.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Least-Squares Regression‬
URL: https://phet-dev.colorado.edu/html/least-squares-regression/1.2.0-dev.1/phet/least-squares-regression_all_phet.html
Version: 1.2.0-dev.1 2024-12-18 13:54:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1280x631
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
@amanda-phet what do you recommend for the 1.2 publication?

**Comment by amanda-phet** [comment]
These accordion boxes should be collapsed on startup as part of the sim's scaffolding.
