### ISSUE TITLE
Chrome Correlation Coefficient Values and Hidden UI

### ISSUE THREAD

**Issue by phet-steele** [phetsims/least-squares-regression#9]
This has only happened in Chrome. Directly overlapping two dots causes odd behavior and can cause the UI to disappear, yet still be functional. The correlation coefficient also is displayed as either NaN or Infinity. Reproducing this can be tricky, but all that needs to happen is getting two dots right on top of each other, and there must not be other dots present. Tested in Win 8.1

Video:
https://drive.google.com/file/d/0B3HJopSo_QqLQ2Q2bUpJZm9tYW8/view?usp=sharing

Troubleshooting information:
Name: Least-Squares Regression
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-dev.6/least-squares-regression_en.html
Version: 1.0.0-dev.6
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by veillette** [comment]
fixed and tested so closing
