### ISSUE TITLE
Screen doesn't pan when dragging data point 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/least-squares-regression#91]
**Testing on macOS 15.1.1 and safari 18.1.1**

For https://github.com/phetsims/qa/issues/1190, after zooming in the screen doesn't pan while dragging a data point around. This happens when removing the data point from the bucket and while moving points around the play area. The screen does pan when dragging the slider thumbs up/down.

**Steps:** 
1. Zoom in
2. Grab a data point from the bucket and try and move it to the right to force the screen to pan

**Comment by samreid** [comment]
I completed https://github.com/phetsims/least-squares-regression/issues/95 and now zoomed-in panning follows the particle after dropped, but not in the createForwardingListener step.

After adding the argument, both seem fixed. Closing.
