### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/least-squares-regression#96]
There seems to be a sizable memory leak in the dev version. For https://github.com/phetsims/qa/issues/1190
<img width="344" alt="leak" src="https://github.com/user-attachments/assets/010ff45a-90cc-4085-8e6c-78411fb2da90" />

**Comment by samreid** [comment]
Looking better after changes here and #93, 

<img width="343" alt="image" src="https://github.com/user-attachments/assets/426d7c78-176a-4e4d-9914-1f8b6d632ee2" />

**Comment by samreid** [comment]
@KatieWoe can you please check phettest to see if this is doing better now? Please close if ok.

**Comment by KatieWoe** [comment]
Looks much better on main
<img width="351" alt="muchbetter" src="https://github.com/user-attachments/assets/13d7ed72-6648-46e7-bcc8-c21dcd947821" />
